# Site
name: "DeltaScream Blog"
title: "DeltaScream Blog"
description: "En este lugar subo escritos, monólogos, articulos sobre programacion, cuentos breves y demas."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: neira9919@gmail.com

# Authors
authors:
  DeltaScream:
    name: DeltaScream
    display_name: DeltaScream
    avatar: 'assets/images/avatar-delta.png'
    email: neira9919@gmail.com
    web: https://www.neira9919.github.io
    twitter: https://www.instagram.com/neira9919/?hl=es-la
    description: "El autor de el 90% del material que veras en el sitio. Me encanta escribir, programar y aprender cosas nuevas. Tambien me encanta el arte, la fotografia y la musica.
    Veras un poco de todo eso en este blog. Deltascream es el nick que suelo utilizar, por ahora, tambien como seudónimo."
  aux:
    name: aux
    display_name: aux    
    avatar: 'assets/images/avatar.png'
    email: aux@gmail.com
    web: #
    twitter: #
    description: "Este autor queda como variante auxiliar en caso de que añada texto que no es de mi propiedad. En dicho caso el articulo en cuestion mencionara la fuente citada."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
